steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - '-c'
    - >
      gcloud beta deploy releases create rel-$(date +%y%m%d-%s)
      --delivery-pipeline=my-demo-app-1 
      --region=us-central1
